### ISSUE TITLE
doesn't scrobble when in repeat mode

### ISSUE THREAD

**Issue by ghost** [InputUsername/rescrobbled#7]

**Comment by InputUsername** [comment]
Do you mean single song repeat? I believe I intentionally prevented scrobbling the same song multiple times, since it's not that easy to detect if a song has started again (as opposed to someone rewinding the track progress). Do you have a solution?

**Comment by treeshateorcs** [comment]
I've solved it once in Go, but I had a proper timer library, which doesn't seem to exist in Rust (I couldn't find it)
you can see my solution in this file
https://github.com/nlamirault/jam/blob/master/ui/player.go

**Comment by InputUsername** [comment]
Thanks for the link. Unfortunately I'm not fluent in Go.

This is a pretty hard problem to solve though, some players (including the official Spotify one) don't report current track position.

I'll take a better look at this.

**Comment by treeshateorcs** [comment]
>don't report current track position.

that is what a timer is for

**Comment by InputUsername** [comment]
OK, I think I have a solution, let me know what you think.

In single song repeat mode:
- count playtime;
- if past the minimal play time required for scrobbling, then scrobble;
- if past the song duration, restart counting.

This might get out of sync though. Eg. because the song duration doesn't match up with the poll interval, or because the user starts seeking around in the track.

In normal mode:
- current behavior (count playtime and scrobble after minimal playtime has passed)

**Comment by treeshateorcs** [comment]
do players report when they are in single repeat mode?

**Comment by InputUsername** [comment]
Hmm, Spotify doesn't appear to do so actually, so that idea doesn't work. Do you have any other ideas?

**Comment by InputUsername** [comment]
Maybe simply checking if we're past the song duration, scrobble, and restart counting from there would work? That can still get out of sync but should work.

**Comment by treeshateorcs** [comment]
1. time listening time
2. pause timer if paused
3. scrobble on song change

**Comment by treeshateorcs** [comment]
to elaborate on 2. :
timer may not be paused, but there should be another special pause timer that times how much time has passed since playback pause and then subtract that time from the first timer

**Comment by InputUsername** [comment]
Yeah, that's more or less the current behavior:
- poll every 0.5 seconds, and increase a timer by this much;
- if paused, don't increase timer; (clients do report playing/paused status correctly)
- if we're past the minimum playing time* scrobble the song immediately (instead of on song change);
- also keep track of whether the current song has already been scrobbled.

By default minimum playing time is at least half the song length, or 4 minutes, whichever comes first.

Proposed behavior is adding a step:
- if we're past the song length, and the song is still the same, reset the timer to 0 and reset the "already scrobbled" status to false.

**Comment by treeshateorcs** [comment]
scrobbling on song change eliminates the need for point 4

also i think that is how it should be done

also why is there any reason for such an interval? why not a whole second?

**Comment by InputUsername** [comment]
By song change, do you mean simply after the duration has passed?

I think I've tried using [`mpris::ProgressTracker`](https://docs.rs/mpris/2.0.0-rc1/mpris/struct.ProgressTracker.html) before, but I'm not sure if it correctly reported that the same song has started again.

The interval is arbitrary -- my idea was that half a second would be slightly more accurate in reporting song progress/song change, but it doesn't really matter :laughing:

**Comment by treeshateorcs** [comment]
no I mean

if (new song != old song)
    if ( timer > 50% of song length)
        scrobble

**Comment by treeshateorcs** [comment]
well that was stupid. we are talking about whenn new song == old song after all

**Comment by InputUsername** [comment]
Yeah, so it's difficult to detect if the song has looped without timing/loop status information.
I don't know if cmus/ncspot report song position/loop status.
If yes, there are 2 options:
1. My solution above; check if we're past the song's duration, and if so, reset the time counter and "already scrobbled" status.
This very easily gets out of sync if you start playing the song at some other position than 0:00, or if you start seeking around in the song.
2. Use timing information provided by the player, and add an exception for clients that don't support  this.

I'm inclined to go with option 1, because it's way less complex

**Comment by treeshateorcs** [comment]
Okay, so I wrote something. Initially I wanted to write my own scrobbler, because it seems easier then refactor and edit your mainloop.rs file, but then got lazy and changed my mind, but I implemented what this issue is about, namely single-repeat scrobbles using a timer, so please take a look, and if you are interested (I am) - rewrite your mainloop according to my main.rs. if you have any questions feel free to ask 

https://github.com/treeshateorcs/mpris-scrobbler/blob/master/src/main.rs
